language: generic
sudo: required

services:
  - docker

before-install:
  - docker build -t bobzhangmba/docker-react -f Dockerfile.dev .

script:
  # - docker run bobzhangmba/docker-react npm run test -- --coverage
  - docker run -e CI=true bobzhangmba/docker-react npm run test
